# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import controller_service_pb2 as proto_dot_controller__service__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/controller_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControllerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFleetStatus = channel.unary_unary(
                '/controller.ControllerService/GetFleetStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_controller__service__pb2.GetFleetStatusResponse.FromString,
                _registered_method=True)
        self.InitGame = channel.unary_unary(
                '/controller.ControllerService/InitGame',
                request_serializer=proto_dot_controller__service__pb2.InitGameRequest.SerializeToString,
                response_deserializer=proto_dot_controller__service__pb2.InitGameResponse.FromString,
                _registered_method=True)
        self.DestroyTokyoBay = channel.unary_unary(
                '/controller.ControllerService/DestroyTokyoBay',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_controller__service__pb2.DestroyTokyoBayResponse.FromString,
                _registered_method=True)
        self.GetPodUrl = channel.unary_unary(
                '/controller.ControllerService/GetPodUrl',
                request_serializer=proto_dot_controller__service__pb2.GetPodUrlRequest.SerializeToString,
                response_deserializer=proto_dot_controller__service__pb2.GetPodUrlResponse.FromString,
                _registered_method=True)
        self.DestroyAll = channel.unary_unary(
                '/controller.ControllerService/DestroyAll',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_controller__service__pb2.DestroyAllResponse.FromString,
                _registered_method=True)
        self.Relocate = channel.unary_unary(
                '/controller.ControllerService/Relocate',
                request_serializer=proto_dot_controller__service__pb2.RelocateRequest.SerializeToString,
                response_deserializer=proto_dot_controller__service__pb2.RelocateResponse.FromString,
                _registered_method=True)
        self.DestroyPod = channel.unary_unary(
                '/controller.ControllerService/DestroyPod',
                request_serializer=proto_dot_controller__service__pb2.DestroyPodRequest.SerializeToString,
                response_deserializer=proto_dot_controller__service__pb2.DestroyPodResponse.FromString,
                _registered_method=True)
        self.GetNodeState = channel.unary_unary(
                '/controller.ControllerService/GetNodeState',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_controller__service__pb2.GetNodeStateResponse.FromString,
                _registered_method=True)


class ControllerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFleetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyTokyoBay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPodUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Relocate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyPod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodeState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFleetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFleetStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_controller__service__pb2.GetFleetStatusResponse.SerializeToString,
            ),
            'InitGame': grpc.unary_unary_rpc_method_handler(
                    servicer.InitGame,
                    request_deserializer=proto_dot_controller__service__pb2.InitGameRequest.FromString,
                    response_serializer=proto_dot_controller__service__pb2.InitGameResponse.SerializeToString,
            ),
            'DestroyTokyoBay': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyTokyoBay,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_controller__service__pb2.DestroyTokyoBayResponse.SerializeToString,
            ),
            'GetPodUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPodUrl,
                    request_deserializer=proto_dot_controller__service__pb2.GetPodUrlRequest.FromString,
                    response_serializer=proto_dot_controller__service__pb2.GetPodUrlResponse.SerializeToString,
            ),
            'DestroyAll': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyAll,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_controller__service__pb2.DestroyAllResponse.SerializeToString,
            ),
            'Relocate': grpc.unary_unary_rpc_method_handler(
                    servicer.Relocate,
                    request_deserializer=proto_dot_controller__service__pb2.RelocateRequest.FromString,
                    response_serializer=proto_dot_controller__service__pb2.RelocateResponse.SerializeToString,
            ),
            'DestroyPod': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyPod,
                    request_deserializer=proto_dot_controller__service__pb2.DestroyPodRequest.FromString,
                    response_serializer=proto_dot_controller__service__pb2.DestroyPodResponse.SerializeToString,
            ),
            'GetNodeState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodeState,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_controller__service__pb2.GetNodeStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'controller.ControllerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('controller.ControllerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControllerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFleetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.ControllerService/GetFleetStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_controller__service__pb2.GetFleetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.ControllerService/InitGame',
            proto_dot_controller__service__pb2.InitGameRequest.SerializeToString,
            proto_dot_controller__service__pb2.InitGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyTokyoBay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.ControllerService/DestroyTokyoBay',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_controller__service__pb2.DestroyTokyoBayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPodUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.ControllerService/GetPodUrl',
            proto_dot_controller__service__pb2.GetPodUrlRequest.SerializeToString,
            proto_dot_controller__service__pb2.GetPodUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.ControllerService/DestroyAll',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_controller__service__pb2.DestroyAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Relocate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.ControllerService/Relocate',
            proto_dot_controller__service__pb2.RelocateRequest.SerializeToString,
            proto_dot_controller__service__pb2.RelocateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyPod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.ControllerService/DestroyPod',
            proto_dot_controller__service__pb2.DestroyPodRequest.SerializeToString,
            proto_dot_controller__service__pb2.DestroyPodResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodeState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/controller.ControllerService/GetNodeState',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_controller__service__pb2.GetNodeStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
