"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetFleetStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FLEET_STATUS_FIELD_NUMBER: builtins.int
    @property
    def fleet_status(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        fleet_status: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["fleet_status", b"fleet_status"]) -> None: ...

global___GetFleetStatusResponse = GetFleetStatusResponse

@typing.final
class PlayerInput(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLAYER_ID_FIELD_NUMBER: builtins.int
    POD_NAME_FIELD_NUMBER: builtins.int
    player_id: builtins.str
    pod_name: builtins.str
    def __init__(
        self,
        *,
        player_id: builtins.str = ...,
        pod_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["player_id", b"player_id", "pod_name", b"pod_name"]) -> None: ...

global___PlayerInput = PlayerInput

@typing.final
class InitGameRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLAYERS_FIELD_NUMBER: builtins.int
    @property
    def players(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PlayerInput]: ...
    def __init__(
        self,
        *,
        players: collections.abc.Iterable[global___PlayerInput] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["players", b"players"]) -> None: ...

global___InitGameRequest = InitGameRequest

@typing.final
class Player(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLAYER_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    POD_URL_FIELD_NUMBER: builtins.int
    player_id: builtins.str
    name: builtins.str
    pod_url: builtins.str
    def __init__(
        self,
        *,
        player_id: builtins.str = ...,
        name: builtins.str = ...,
        pod_url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "player_id", b"player_id", "pod_url", b"pod_url"]) -> None: ...

global___Player = Player

@typing.final
class InitGameResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLAYERS_FIELD_NUMBER: builtins.int
    LOCATIONS_FIELD_NUMBER: builtins.int
    @property
    def players(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Player]: ...
    @property
    def locations(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        players: collections.abc.Iterable[global___Player] | None = ...,
        locations: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["locations", b"locations", "players", b"players"]) -> None: ...

global___InitGameResponse = InitGameResponse

@typing.final
class DestroyTokyoBayResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLAYER_ID_FIELD_NUMBER: builtins.int
    @property
    def player_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        player_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["player_id", b"player_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["player_id", b"player_id"]) -> None: ...

global___DestroyTokyoBayResponse = DestroyTokyoBayResponse

@typing.final
class GetPodUrlRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLAYER_ID_FIELD_NUMBER: builtins.int
    player_id: builtins.str
    def __init__(
        self,
        *,
        player_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["player_id", b"player_id"]) -> None: ...

global___GetPodUrlRequest = GetPodUrlRequest

@typing.final
class GetPodUrlResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POD_URL_FIELD_NUMBER: builtins.int
    pod_url: builtins.str
    def __init__(
        self,
        *,
        pod_url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pod_url", b"pod_url"]) -> None: ...

global___GetPodUrlResponse = GetPodUrlResponse

@typing.final
class DestroyAllResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: builtins.str
    def __init__(
        self,
        *,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___DestroyAllResponse = DestroyAllResponse

@typing.final
class RelocateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLAYER_ID_FIELD_NUMBER: builtins.int
    TARGET_LOCATION_FIELD_NUMBER: builtins.int
    CURRENT_LOCATION_FIELD_NUMBER: builtins.int
    player_id: builtins.str
    target_location: builtins.str
    current_location: builtins.str
    def __init__(
        self,
        *,
        player_id: builtins.str = ...,
        target_location: builtins.str = ...,
        current_location: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["current_location", b"current_location", "player_id", b"player_id", "target_location", b"target_location"]) -> None: ...

global___RelocateRequest = RelocateRequest

@typing.final
class RelocateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: builtins.str
    def __init__(
        self,
        *,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___RelocateResponse = RelocateResponse

@typing.final
class DestroyPodRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PLAYER_ID_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    player_id: builtins.str
    location: builtins.str
    def __init__(
        self,
        *,
        player_id: builtins.str = ...,
        location: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["location", b"location", "player_id", b"player_id"]) -> None: ...

global___DestroyPodRequest = DestroyPodRequest

@typing.final
class DestroyPodResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: builtins.str
    def __init__(
        self,
        *,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___DestroyPodResponse = DestroyPodResponse

@typing.final
class GetNodeStateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKYO_CITY_FIELD_NUMBER: builtins.int
    TOKYO_BAY_FIELD_NUMBER: builtins.int
    OUTSIDE_FIELD_NUMBER: builtins.int
    tokyo_city: builtins.str
    tokyo_bay: builtins.str
    @property
    def outside(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        tokyo_city: builtins.str = ...,
        tokyo_bay: builtins.str = ...,
        outside: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["outside", b"outside", "tokyo_bay", b"tokyo_bay", "tokyo_city", b"tokyo_city"]) -> None: ...

global___GetNodeStateResponse = GetNodeStateResponse
